// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/assets_generator
// **************************************************************************
// ignore_for_file: constant_identifier_names

class Assets {
  const Assets._();

  /// {@macro assets_generator.assets_images_home_png.preview}
  static const String assets_images_home_png = 'assets/images/home.png';

  static const String assets_sounds_aaa_mp3 = 'assets/sounds/aaa.mp3';

  static const String assets_sounds_alert_mp3 = 'assets/sounds/alert.mp3';

  static const String assets_sounds_bell_mp3 = 'assets/sounds/bell.mp3';

  static const String assets_sounds_digital_mp3 = 'assets/sounds/digital.mp3';

  static const String assets_sounds_gentle_mp3 = 'assets/sounds/gentle.mp3';

  static const String assets_sounds_nature_mp3 = 'assets/sounds/nature.mp3';

  static const String assets_web_timer_digit_timer_flip_timer_html =
      'assets/web/timer/digit-timer/flip_timer.html';
}
